project:
  name: quickstart-mongodb-atlas-analytics-amazon-sagemaker-integration
  owner: quickstart-eng@amazon.com
  package_lambda: false
  shorten_stack_name: true
tests:
  mdb-atlas-sagemaker:
    regions:
    - ap-south-1
    - us-east-1
    parameters:
      AtlasProjectID: override
      CollectionName: override
      DatabaseName: override
      ModelDataS3URI: override
      ModelECRImageURI: override
      MongoEndpoint: override
      PrivateKey: override
      PublicKey: override
      PullLambdaECRImageURI: override
      PushLambdaECRImageURI: override
      RealmAppID: override
      ServiceID: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-mongodb-atlas-analytics-amazon-sagemaker-integration/
    template: templates/mongodb-sagemaker-analytics-main.template.yaml